name: CMake

on:
  pull_request:
    branches: [ "*" ]

env:
  BUILD_TYPE: Release
  HYRISE_HEADLESS_SETUP: true

jobs:
  build_linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies.
      run: ${{github.workspace}}/install_dependencies.sh

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  build_macos:
    # we need to configure clang(++) as a compiler for the Cmake build
    # it might be possible to do this prettily with GitHub Actions matrices
    # but for getting it working two different jobs will have to suffice
    runs-on: macos_latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies.
      run: ${{github.workspace}}/install_dependencies.sh

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


