name: CMake GH Actions

on: push

jobs:
  cmake:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Project
        run: git clone --recursive https://github.com/hyrise-mp-22-23/hyrise.git hyrise && hyrise
