name: CMake GH Actions

on: push

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Update Submodules
        run: git clone --recursive https://github.com/hyrise-mp-22-23/hyrise.git hyrise && cd hyrise && git checkout ${GITHUB_REF##*/}

      - name: Install Dependencies
        run: sudo apt-get install --no-install-recommends -y autoconf bash-completion bc clang-11 clang-14 clang-format-14 clang-tidy-14 cmake curl dos2unix g++-9 gcc-9 g++-11 gcc-11 gcovr git graphviz libboost-all-dev libhwloc-dev libncurses5-dev libnuma-dev libnuma1 libpq-dev libreadline-dev libsqlite3-dev libtbb-dev lld man ninja-build parallel postgresql-server-dev-all python3 python3-pip valgrind

      - name: Run CMake
        run: |
            cd ${{github.workspace}}/hyrise/
            mkdir cmake-build-debug && cd cmake-build-debug
            cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
      
      - name: Run Make
        run: |
            cd ${{github.workspace}}/hyrise/cmake-build-debug
            make hyriseConsole -j4
            echo "Build Finished Successfully"


