name: CMake GH Actions

on: push

jobs:
  cmake:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Project
        run: git clone --recursive https://github.com/hyrise-mp-22-23/hyrise.git hyrise

      - name: Install Dependencies
        run: |
            cd /home/runner/work/hyrise/hyrise
            pwd
            chmod +x install_dependencies.sh
            bash ./install_dependenies.sh